<?php return array (
  'keys' => 
  array (
    0 => '{www image}',
    1 => '{www themes}',
    2 => '{www shared plugins}',
    3 => '{www shared assets}',
    4 => '{cache}',
    5 => '{logs}',
    6 => '{sessions}',
    7 => '{upload temp}',
    8 => '{uploads}',
    9 => '{downloads}',
    10 => '{viewpath}',
    11 => '{www}',
    12 => '{rootpath}',
    13 => '{apppath}',
    14 => '{application}',
    15 => '{basepath}',
    16 => '{environment}',
    17 => '{fcpath}',
    18 => '{sysdir}',
    19 => '{orangepath}',
    20 => '{login}',
    21 => '{logout}',
    22 => '{dashboard}',
    23 => '{homepage}',
  ),
  'values' => 
  array (
    0 => '/images',
    1 => '/theme',
    2 => '/plugins',
    3 => '/assets',
    4 => '/var/cache',
    5 => '/var/logs',
    6 => '/var/sessions',
    7 => '/var/upload_temp',
    8 => '/var/uploads',
    9 => '/var/downloads',
    10 => '/var/www/www/app/application/views/',
    11 => '/var/www/www/app/public',
    12 => '/var/www/www/app',
    13 => '/var/www/www/app/application/',
    14 => '/var/www/www/app/application/',
    15 => '/var/www/www/app/vendor/codeigniter/framework/system/',
    16 => 'development',
    17 => '/var/www/www/app/public/',
    18 => 'system',
    19 => '/var/www/www/app/packages/projectorangebox/orange',
    20 => 'login',
    21 => 'login/inverted',
    22 => '',
    23 => '',
  ),
);