<?php 

$baseDir = dirname(__DIR__);

return array (
  'orange' => 
  array (
    'CI_Benchmark' => $baseDir.'/vendor/codeigniter/framework/system/core/Benchmark.php',
    'CI_CodeIgniter' => $baseDir.'/vendor/codeigniter/framework/system/core/CodeIgniter.php',
    'CI_Common' => $baseDir.'/vendor/codeigniter/framework/system/core/Common.php',
    'CI_Config' => $baseDir.'/vendor/codeigniter/framework/system/core/Config.php',
    'CI_Controller' => $baseDir.'/vendor/codeigniter/framework/system/core/Controller.php',
    'CI_Exceptions' => $baseDir.'/vendor/codeigniter/framework/system/core/Exceptions.php',
    'CI_Hooks' => $baseDir.'/vendor/codeigniter/framework/system/core/Hooks.php',
    'CI_Input' => $baseDir.'/vendor/codeigniter/framework/system/core/Input.php',
    'CI_Lang' => $baseDir.'/vendor/codeigniter/framework/system/core/Lang.php',
    'CI_Loader' => $baseDir.'/vendor/codeigniter/framework/system/core/Loader.php',
    'CI_Log' => $baseDir.'/vendor/codeigniter/framework/system/core/Log.php',
    'CI_Model' => $baseDir.'/vendor/codeigniter/framework/system/core/Model.php',
    'CI_Output' => $baseDir.'/vendor/codeigniter/framework/system/core/Output.php',
    'CI_Router' => $baseDir.'/vendor/codeigniter/framework/system/core/Router.php',
    'CI_Security' => $baseDir.'/vendor/codeigniter/framework/system/core/Security.php',
    'CI_URI' => $baseDir.'/vendor/codeigniter/framework/system/core/URI.php',
    'CI_Utf8' => $baseDir.'/vendor/codeigniter/framework/system/core/Utf8.php',
    'CI_Calendar' => $baseDir.'/vendor/codeigniter/framework/system/libraries/Calendar.php',
    'CI_Cart' => $baseDir.'/vendor/codeigniter/framework/system/libraries/Cart.php',
    'CI_Driver' => $baseDir.'/vendor/codeigniter/framework/system/libraries/Driver.php',
    'CI_Email' => $baseDir.'/vendor/codeigniter/framework/system/libraries/Email.php',
    'CI_Encrypt' => $baseDir.'/vendor/codeigniter/framework/system/libraries/Encrypt.php',
    'CI_Encryption' => $baseDir.'/vendor/codeigniter/framework/system/libraries/Encryption.php',
    'CI_Form_validation' => $baseDir.'/vendor/codeigniter/framework/system/libraries/Form_validation.php',
    'CI_Ftp' => $baseDir.'/vendor/codeigniter/framework/system/libraries/Ftp.php',
    'CI_Image_lib' => $baseDir.'/vendor/codeigniter/framework/system/libraries/Image_lib.php',
    'CI_Javascript' => $baseDir.'/vendor/codeigniter/framework/system/libraries/Javascript.php',
    'CI_Migration' => $baseDir.'/vendor/codeigniter/framework/system/libraries/Migration.php',
    'CI_Pagination' => $baseDir.'/vendor/codeigniter/framework/system/libraries/Pagination.php',
    'CI_Parser' => $baseDir.'/vendor/codeigniter/framework/system/libraries/Parser.php',
    'CI_Profiler' => $baseDir.'/vendor/codeigniter/framework/system/libraries/Profiler.php',
    'CI_Table' => $baseDir.'/vendor/codeigniter/framework/system/libraries/Table.php',
    'CI_Trackback' => $baseDir.'/vendor/codeigniter/framework/system/libraries/Trackback.php',
    'CI_Typography' => $baseDir.'/vendor/codeigniter/framework/system/libraries/Typography.php',
    'CI_Unit_test' => $baseDir.'/vendor/codeigniter/framework/system/libraries/Unit_test.php',
    'CI_Upload' => $baseDir.'/vendor/codeigniter/framework/system/libraries/Upload.php',
    'CI_User_agent' => $baseDir.'/vendor/codeigniter/framework/system/libraries/User_agent.php',
    'CI_Xmlrpc' => $baseDir.'/vendor/codeigniter/framework/system/libraries/Xmlrpc.php',
    'CI_Xmlrpcs' => $baseDir.'/vendor/codeigniter/framework/system/libraries/Xmlrpcs.php',
    'CI_Zip' => $baseDir.'/vendor/codeigniter/framework/system/libraries/Zip.php',
    'validate_filter_item_no_core' => $baseDir.'/packages/quadratec/stock-status-check/libraries/validations/Validate_filter_item_no_core.php',
    'validate_md5' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_md5.php',
    'validate_if_empty' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_if_empty.php',
    'validate_ip' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_ip.php',
    'validate_dollars' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_dollars.php',
    'validate_array_between' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_array_between.php',
    'validate_access' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_access.php',
    'validate_max_width' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_max_width.php',
    'validate_exact_width' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_exact_width.php',
    'validate_foldername' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_foldername.php',
    'validate_max_dim' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_max_dim.php',
    'validate_valid_dob' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_valid_dob.php',
    'validate_matches_pattern' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_matches_pattern.php',
    'validate_min_dim' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_min_dim.php',
    'validate_is_dir' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_is_dir.php',
    'validate_is_after_date' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_is_after_date.php',
    'validate_url' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_url.php',
    'validate_is_before_date' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_is_before_date.php',
    'validate_slug' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_slug.php',
    'validate_is_between' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_is_between.php',
    'validate_exists' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_exists.php',
    'validate_record_match' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_record_match.php',
    'validate_valid_date' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_valid_date.php',
    'validate_boolean' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_boolean.php',
    'validate_height' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_height.php',
    'validate_float' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_float.php',
    'validate_image_ratio' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_image_ratio.php',
    'validate_file_size_min' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_file_size_min.php',
    'validate_alpha_extra' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_alpha_extra.php',
    'validate_primary_exists' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_primary_exists.php',
    'validate_phone' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_phone.php',
    'validate_is_outside' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_is_outside.php',
    'validate_array_max' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_array_max.php',
    'validate_even' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_even.php',
    'validate_not_one_of' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_not_one_of.php',
    'validate_allowed_types' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_allowed_types.php',
    'validate_is_serialized_str' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_is_serialized_str.php',
    'validate_ends_with' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_ends_with.php',
    'validate_is_not' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_is_not.php',
    'validate_valid_datetime' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_valid_datetime.php',
    'validate_min_height' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_min_height.php',
    'validate_is_uniquem' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_is_uniquem.php',
    'validate_credit_card' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_credit_card.php',
    'validate_zip' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_zip.php',
    'validate_file_size_max' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_file_size_max.php',
    'validate_hexcolor' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_hexcolor.php',
    'validate_array_count' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_array_count.php',
    'validate_percent' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_percent.php',
    'validate_is_closure' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_is_closure.php',
    'validate_symbolic_link' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_symbolic_link.php',
    'validate_int' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_int.php',
    'validate_hmac' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_hmac.php',
    'validate_required_without' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_required_without.php',
    'validate_is_a_primary' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_is_a_primary.php',
    'validate_is_bol' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_is_bol.php',
    'validate_array_min' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_array_min.php',
    'validate_is_image_file' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_is_image_file.php',
    'validate_uri' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_uri.php',
    'validate_contains' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_contains.php',
    'validate_readable' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_readable.php',
    'validate_required_with' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_required_with.php',
    'validate_min_width' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_min_width.php',
    'validate_exact_height' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_exact_height.php',
    'validate_check_captcha' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_check_captcha.php',
    'validate_max_height' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_max_height.php',
    'validate_version' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_version.php',
    'validate_writable' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_writable.php',
    'validate_exact_dim' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_exact_dim.php',
    'validate_odd' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_odd.php',
    'validate_width' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_width.php',
    'validate_filename' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_filename.php',
    'validate_starts_with' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_starts_with.php',
    'validate_is_between_dates' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_is_between_dates.php',
    'validate_is_json_str' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_is_json_str.php',
    'validate_is_file' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_is_file.php',
    'validate_valid_time' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/validations/Validate_valid_time.php',
    'validate_decimal' => $baseDir.'/packages/projectorangebox/orange/libraries/validations/Validate_decimal.php',
    'validate_valid_emails' => $baseDir.'/packages/projectorangebox/orange/libraries/validations/Validate_valid_emails.php',
    'validate_valid_ip' => $baseDir.'/packages/projectorangebox/orange/libraries/validations/Validate_valid_ip.php',
    'validate_max_length' => $baseDir.'/packages/projectorangebox/orange/libraries/validations/Validate_max_length.php',
    'validate_matches' => $baseDir.'/packages/projectorangebox/orange/libraries/validations/Validate_matches.php',
    'validate_valid_url' => $baseDir.'/packages/projectorangebox/orange/libraries/validations/Validate_valid_url.php',
    'validate_integer' => $baseDir.'/packages/projectorangebox/orange/libraries/validations/Validate_integer.php',
    'validate_greater_than_equal_to' => $baseDir.'/packages/projectorangebox/orange/libraries/validations/Validate_greater_than_equal_to.php',
    'validate_alpha' => $baseDir.'/packages/projectorangebox/orange/libraries/validations/Validate_alpha.php',
    'validate_is_unique' => $baseDir.'/packages/projectorangebox/orange/libraries/validations/Validate_is_unique.php',
    'validate_regex_match' => $baseDir.'/packages/projectorangebox/orange/libraries/validations/Validate_regex_match.php',
    'validate_valid_base64' => $baseDir.'/packages/projectorangebox/orange/libraries/validations/Validate_valid_base64.php',
    'validate_alpha_dash' => $baseDir.'/packages/projectorangebox/orange/libraries/validations/Validate_alpha_dash.php',
    'validate_alpha_numeric_spaces' => $baseDir.'/packages/projectorangebox/orange/libraries/validations/Validate_alpha_numeric_spaces.php',
    'validate_alpha_numeric' => $baseDir.'/packages/projectorangebox/orange/libraries/validations/Validate_alpha_numeric.php',
    'validate_exact_length' => $baseDir.'/packages/projectorangebox/orange/libraries/validations/Validate_exact_length.php',
    'validate_alpha_space' => $baseDir.'/packages/projectorangebox/orange/libraries/validations/Validate_alpha_space.php',
    'validate_less_than' => $baseDir.'/packages/projectorangebox/orange/libraries/validations/Validate_less_than.php',
    'validate_in_list' => $baseDir.'/packages/projectorangebox/orange/libraries/validations/Validate_in_list.php',
    'validate_greater_than' => $baseDir.'/packages/projectorangebox/orange/libraries/validations/Validate_greater_than.php',
    'validate_is_natural' => $baseDir.'/packages/projectorangebox/orange/libraries/validations/Validate_is_natural.php',
    'validate_differs' => $baseDir.'/packages/projectorangebox/orange/libraries/validations/Validate_differs.php',
    'validate_valid_email' => $baseDir.'/packages/projectorangebox/orange/libraries/validations/Validate_valid_email.php',
    'validate_is_natural_no_zero' => $baseDir.'/packages/projectorangebox/orange/libraries/validations/Validate_is_natural_no_zero.php',
    'validate_min_length' => $baseDir.'/packages/projectorangebox/orange/libraries/validations/Validate_min_length.php',
    'validate_numeric' => $baseDir.'/packages/projectorangebox/orange/libraries/validations/Validate_numeric.php',
    'validate_required' => $baseDir.'/packages/projectorangebox/orange/libraries/validations/Validate_required.php',
    'validate_less_than_equal_to' => $baseDir.'/packages/projectorangebox/orange/libraries/validations/Validate_less_than_equal_to.php',
    'pear_menu_li' => $baseDir.'/application/libraries/pear_plugins/Pear_menu_li.php',
    'pear_lowercase' => $baseDir.'/application/libraries/pear_plugins/Pear_lowercase.php',
    'pear_status_dropdown' => $baseDir.'/packages/quadratec/backorder/libraries/pear_plugins/Pear_status_dropdown.php',
    'pear_open_pos' => $baseDir.'/packages/quadratec/backorder/libraries/pear_plugins/Pear_open_pos.php',
    'pear_load_po_details' => $baseDir.'/packages/quadratec/backorder/libraries/pear_plugins/Pear_load_po_details.php',
    'pear_explode_pos' => $baseDir.'/packages/quadratec/backorder/libraries/pear_plugins/Pear_explode_pos.php',
    'pear_load_po_header' => $baseDir.'/packages/quadratec/backorder/libraries/pear_plugins/Pear_load_po_header.php',
    'pear_macs_date' => $baseDir.'/packages/quadratec/backorder/libraries/pear_plugins/Pear_macs_date.php',
    'pear_dropship' => $baseDir.'/packages/quadratec/drop-ships/libraries/pear_plugins/Pear_dropship.php',
    'pear_user_exists' => $baseDir.'/packages/projectorangebox/register/libraries/pear_plugins/Pear_user_exists.php',
    'pear_json_value' => $baseDir.'/packages/projectorangebox/register/libraries/pear_plugins/Pear_json_value.php',
    'pear_config_viewer_value' => $baseDir.'/packages/projectorangebox/config-viewer/libraries/pear_plugins/Pear_config_viewer_value.php',
    'pear_cache_expires' => $baseDir.'/packages/projectorangebox/cache-viewer/libraries/pear_plugins/Pear_cache_expires.php',
    'pear_goback_button' => $baseDir.'/packages/projectorangebox/theme-orange/libraries/pear_plugins/Pear_goback_button.php',
    'pear_date_picker' => $baseDir.'/packages/projectorangebox/theme-orange/libraries/pear_plugins/Pear_date_picker.php',
    'pear_date' => $baseDir.'/packages/projectorangebox/theme-orange/libraries/pear_plugins/Pear_date.php',
    'pear_combobox' => $baseDir.'/packages/projectorangebox/theme-orange/libraries/pear_plugins/Pear_combobox.php',
    'pear_header_button' => $baseDir.'/packages/projectorangebox/theme-orange/libraries/pear_plugins/Pear_header_button.php',
    'pear_search_sort_field' => $baseDir.'/packages/projectorangebox/theme-orange/libraries/pear_plugins/Pear_search_sort_field.php',
    'pear_bootstrap_wysiwyg' => $baseDir.'/packages/projectorangebox/theme-orange/libraries/pear_plugins/Pear_bootstrap_wysiwyg.php',
    'pear_color_value' => $baseDir.'/packages/projectorangebox/theme-orange/libraries/pear_plugins/Pear_color_value.php',
    'pear_select3' => $baseDir.'/packages/projectorangebox/theme-orange/libraries/pear_plugins/Pear_select3.php',
    'pear_color_picker' => $baseDir.'/packages/projectorangebox/theme-orange/libraries/pear_plugins/Pear_color_picker.php',
    'pear_sticky_table_header' => $baseDir.'/packages/projectorangebox/theme-orange/libraries/pear_plugins/Pear_sticky_table_header.php',
    'pear_dt_picker' => $baseDir.'/packages/projectorangebox/theme-orange/libraries/pear_plugins/Pear_dt_picker.php',
    'pear_nestable' => $baseDir.'/packages/projectorangebox/theme-orange/libraries/pear_plugins/Pear_nestable.php',
    'pear_confirm_dialog' => $baseDir.'/packages/projectorangebox/theme-orange/libraries/pear_plugins/Pear_confirm_dialog.php',
    'pear_field_label' => $baseDir.'/packages/projectorangebox/theme-orange/libraries/pear_plugins/Pear_field_label.php',
    'pear_color_block' => $baseDir.'/packages/projectorangebox/theme-orange/libraries/pear_plugins/Pear_color_block.php',
    'pear_fa_dropdown' => $baseDir.'/packages/projectorangebox/theme-orange/libraries/pear_plugins/Pear_fa_dropdown.php',
    'pear_form_tools' => $baseDir.'/packages/projectorangebox/theme-orange/libraries/pear_plugins/Pear_form_tools.php',
    'pear_flash_msg' => $baseDir.'/packages/projectorangebox/theme-orange/libraries/pear_plugins/Pear_flash_msg.php',
    'pear_fa_icon' => $baseDir.'/packages/projectorangebox/theme-orange/libraries/pear_plugins/Pear_fa_icon.php',
    'pear_new_button' => $baseDir.'/packages/projectorangebox/theme-orange/libraries/pear_plugins/Pear_new_button.php',
    'pear_input_mask' => $baseDir.'/packages/projectorangebox/theme-orange/libraries/pear_plugins/Pear_input_mask.php',
    'pear_money' => $baseDir.'/packages/projectorangebox/theme-orange/libraries/pear_plugins/Pear_money.php',
    'pear_role_dropdown' => $baseDir.'/packages/projectorangebox/theme-orange/libraries/pear_plugins/Pear_role_dropdown.php',
    'pear_field_human' => $baseDir.'/packages/projectorangebox/theme-orange/libraries/pear_plugins/Pear_field_human.php',
    'pear_title' => $baseDir.'/packages/projectorangebox/theme-orange/libraries/pear_plugins/Pear_title.php',
    'pear_tab_id' => $baseDir.'/packages/projectorangebox/theme-orange/libraries/pear_plugins/Pear_tab_id.php',
    'pear_keymaster' => $baseDir.'/packages/projectorangebox/theme-orange/libraries/pear_plugins/Pear_keymaster.php',
    'pear_delete_button' => $baseDir.'/packages/projectorangebox/theme-orange/libraries/pear_plugins/Pear_delete_button.php',
    'pear_e' => $baseDir.'/packages/projectorangebox/theme-orange/libraries/pear_plugins/Pear_e.php',
    'pear_datalist' => $baseDir.'/packages/projectorangebox/theme-orange/libraries/pear_plugins/Pear_datalist.php',
    'pear_date_time_picker' => $baseDir.'/packages/projectorangebox/theme-orange/libraries/pear_plugins/Pear_date_time_picker.php',
    'pear_summernote' => $baseDir.'/packages/projectorangebox/theme-orange/libraries/pear_plugins/Pear_summernote.php',
    'pear_form_help' => $baseDir.'/packages/projectorangebox/theme-orange/libraries/pear_plugins/Pear_form_help.php',
    'pear_form_static' => $baseDir.'/packages/projectorangebox/theme-orange/libraries/pear_plugins/Pear_form_static.php',
    'pear_edit_button' => $baseDir.'/packages/projectorangebox/theme-orange/libraries/pear_plugins/Pear_edit_button.php',
    'pear_time_picker' => $baseDir.'/packages/projectorangebox/theme-orange/libraries/pear_plugins/Pear_time_picker.php',
    'pear_locked_field' => $baseDir.'/packages/projectorangebox/theme-orange/libraries/pear_plugins/Pear_locked_field.php',
    'bootstrap_wysiwyg_toolbars/default_toolbar' => $baseDir.'/packages/projectorangebox/theme-orange/libraries/pear_plugins/bootstrap_wysiwyg_toolbars/default_toolbar.php',
    'pear_tab_prepare' => $baseDir.'/packages/projectorangebox/theme-orange/libraries/pear_plugins/Pear_tab_prepare.php',
    'pear_fa_enum_icon' => $baseDir.'/packages/projectorangebox/theme-orange/libraries/pear_plugins/Pear_fa_enum_icon.php',
    'pear_tabs' => $baseDir.'/packages/projectorangebox/theme-orange/libraries/pear_plugins/Pear_tabs.php',
    'pear_rest_form' => $baseDir.'/packages/projectorangebox/theme-orange/libraries/pear_plugins/Pear_rest_form.php',
    'pear_tab_title' => $baseDir.'/packages/projectorangebox/theme-orange/libraries/pear_plugins/Pear_tab_title.php',
    'pear_tab_save' => $baseDir.'/packages/projectorangebox/theme-orange/libraries/pear_plugins/Pear_tab_save.php',
    'pear_catalog_dropdown' => $baseDir.'/packages/projectorangebox/theme-orange/libraries/pear_plugins/Pear_catalog_dropdown.php',
    'pear_catalog_lookup' => $baseDir.'/packages/projectorangebox/theme-orange/libraries/pear_plugins/Pear_catalog_lookup.php',
    'filter_item_no_core' => $baseDir.'/packages/quadratec/stock-status-check/libraries/filters/Filter_item_no_core.php',
    'filter_json' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/filters/Filter_json.php',
    'filter_lowercase' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/filters/Filter_lowercase.php',
    'filter_copy' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/filters/Filter_copy.php',
    'filter_replace' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/filters/Filter_replace.php',
    'filter_hex' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/filters/Filter_hex.php',
    'filter_filename' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/filters/Filter_filename.php',
    'filter_md5' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/filters/Filter_md5.php',
    'filter_bol2bol' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/filters/Filter_bol2bol.php',
    'filter_phone' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/filters/Filter_phone.php',
    'filter_url_safe' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/filters/Filter_url_safe.php',
    'filter_combined' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/filters/Filter_combined.php',
    'filter_url' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/filters/Filter_url.php',
    'filter_xss_clean' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/filters/Filter_xss_clean.php',
    'filter_words' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/filters/Filter_words.php',
    'filter_remove' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/filters/Filter_remove.php',
    'filter_substr' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/filters/Filter_substr.php',
    'filter_strip_tags' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/filters/Filter_strip_tags.php',
    'filter_datauri' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/filters/Filter_datauri.php',
    'filter_strip_image_tags' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/filters/Filter_strip_image_tags.php',
    'filter_uppercase' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/filters/Filter_uppercase.php',
    'filter_encode_php_tags' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/filters/Filter_encode_php_tags.php',
    'filter_email' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/filters/Filter_email.php',
    'filter_array_explode' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/filters/Filter_array_explode.php',
    'filter_array_implode' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/filters/Filter_array_implode.php',
    'filter_bol2int' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/filters/Filter_bol2int.php',
    'filter_strtotime' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/filters/Filter_strtotime.php',
    'filter_img2src' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/filters/Filter_img2src.php',
    'filter_except' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/filters/Filter_except.php',
    'filter_uri' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/filters/Filter_uri.php',
    'filter_float' => $baseDir.'/packages/projectorangebox/orange/libraries/filters/Filter_float.php',
    'filter_trim' => $baseDir.'/packages/projectorangebox/orange/libraries/filters/Filter_trim.php',
    'filter_length' => $baseDir.'/packages/projectorangebox/orange/libraries/filters/Filter_length.php',
    'filter_convert_date' => $baseDir.'/packages/projectorangebox/orange/libraries/filters/Filter_convert_date.php',
    'filter_int' => $baseDir.'/packages/projectorangebox/orange/libraries/filters/Filter_int.php',
    'filter_textarea' => $baseDir.'/packages/projectorangebox/orange/libraries/filters/Filter_textarea.php',
    'filter_str' => $baseDir.'/packages/projectorangebox/orange/libraries/filters/Filter_str.php',
    'filter_slug' => $baseDir.'/packages/projectorangebox/orange/libraries/filters/Filter_slug.php',
    'filter_input' => $baseDir.'/packages/projectorangebox/orange/libraries/filters/Filter_input.php',
    'filter_combobox' => $baseDir.'/packages/projectorangebox/theme-orange/libraries/filters/Filter_combobox.php',
    'loginmiddleware' => $baseDir.'/packages/projectorangebox/login-success/middleware/LoginMiddleware.php',
    'tooltipmiddleware' => $baseDir.'/packages/projectorangebox/tooltips/middleware/TooltipMiddleware.php',
    'publicmiddleware' => $baseDir.'/packages/projectorangebox/theme-orange/middleware/PublicMiddleware.php',
    'guimiddleware' => $baseDir.'/packages/projectorangebox/theme-orange/middleware/GuiMiddleware.php',
    'adminmiddleware' => $baseDir.'/packages/projectorangebox/theme-orange/middleware/AdminMiddleware.php',
    'admin_controller_trait' => $baseDir.'/packages/projectorangebox/theme-orange/controllers/traits/admin_controller_trait.php',
    'admin_acl_controller_trait' => $baseDir.'/packages/projectorangebox/theme-orange/controllers/traits/admin_acl_controller_trait.php',
    'admin_export_controller_trait' => $baseDir.'/packages/projectorangebox/theme-orange/controllers/traits/admin_export_controller_trait.php',
    'my_config' => $baseDir.'/packages/projectorangebox/orange/core/MY_Config.php',
    'my_loader' => $baseDir.'/packages/projectorangebox/orange/core/MY_Loader.php',
    'my_output' => $baseDir.'/packages/projectorangebox/orange/core/MY_Output.php',
    'orange' => $baseDir.'/packages/projectorangebox/orange/core/Orange.php',
    'my_controller' => $baseDir.'/packages/projectorangebox/orange/core/MY_Controller.php',
    'my_model' => $baseDir.'/packages/projectorangebox/orange/core/MY_Model.php',
    'my_router' => $baseDir.'/packages/projectorangebox/orange/core/MY_Router.php',
    'my_log' => $baseDir.'/packages/projectorangebox/orange/core/MY_Log.php',
    'my_input' => $baseDir.'/packages/projectorangebox/orange/core/MY_Input.php',
  ),
  'models' => 
  array (
    'backorder_mgr_history_model' => $baseDir.'/packages/quadratec/backorder/models/Backorder_mgr_history_model.php',
    'item_mast_model' => $baseDir.'/packages/quadratec/backorder/models/Item_mast_model.php',
    'mbfoster_kit_index_model' => $baseDir.'/packages/quadratec/backorder/models/Mbfoster_kit_index_model.php',
    'mbfoster_po_header_model' => $baseDir.'/packages/quadratec/backorder/models/Mbfoster_po_header_model.php',
    'mbfoster_po_details_model' => $baseDir.'/packages/quadratec/backorder/models/Mbfoster_po_details_model.php',
    'mbfoster_item_mast_model' => $baseDir.'/packages/quadratec/backorder/models/Mbfoster_item_mast_model.php',
    'status_model' => $baseDir.'/packages/quadratec/backorder/models/Status_model.php',
    'backorder_buyer_groups_model' => $baseDir.'/packages/quadratec/backorder/models/Backorder_buyer_groups_model.php',
    'mbfoster_edp_to_item_no_core_model' => $baseDir.'/packages/quadratec/backorder/models/Mbfoster_edp_to_item_no_core_model.php',
    'mbfoster_open_pos_model' => $baseDir.'/packages/quadratec/backorder/models/Mbfoster_open_pos_model.php',
    'stock_status_model' => $baseDir.'/packages/quadratec/stock-status-check/models/Stock_status_model.php',
    'dropships_model' => $baseDir.'/packages/quadratec/drop-ships/models/Dropships_model.php',
    'o_forgot_model' => $baseDir.'/packages/projectorangebox/forgot/models/O_forgot_model.php',
    'o_auto_login_model' => $baseDir.'/packages/projectorangebox/remember/models/O_auto_login_model.php',
    'a_register_model' => $baseDir.'/packages/projectorangebox/register/models/A_register_model.php',
    'a_logins_successful_model' => $baseDir.'/packages/projectorangebox/login-success/models/A_logins_successful_model.php',
    'a_tooltips_model' => $baseDir.'/packages/projectorangebox/tooltips/models/A_tooltips_model.php',
    'addon_snippets_model' => $baseDir.'/packages/projectorangebox/general_addons/models/Addon_snippets_model.php',
    'addon_templates_model' => $baseDir.'/packages/projectorangebox/general_addons/models/Addon_templates_model.php',
    'o_role_model' => $baseDir.'/packages/projectorangebox/orange/models/O_role_model.php',
    'o_permission_model' => $baseDir.'/packages/projectorangebox/orange/models/O_permission_model.php',
    'o_user_model' => $baseDir.'/packages/projectorangebox/orange/models/O_user_model.php',
    'database_model' => $baseDir.'/packages/projectorangebox/orange/models/Database_model.php',
    'o_setting_model' => $baseDir.'/packages/projectorangebox/orange/models/O_setting_model.php',
  ),
  'libraries' => 
  array (
    'backorder_lib' => $baseDir.'/packages/quadratec/backorder/libraries/Backorder_lib.php',
    'data_uri' => $baseDir.'/packages/projectorangebox/extra-validations/libraries/Data_uri.php',
    'forgot_tools_lib' => $baseDir.'/packages/projectorangebox/forgot/libraries/Forgot_tools_lib.php',
    'auto_login' => $baseDir.'/packages/projectorangebox/remember/libraries/Auto_login.php',
    'orange_register_library' => $baseDir.'/packages/projectorangebox/register/libraries/Orange_register_library.php',
    'opcachedatamodel' => $baseDir.'/packages/projectorangebox/opcache/libraries/Opcachedatamodel.php',
    'breadcrumbs' => $baseDir.'/packages/projectorangebox/librarian/libraries/Breadcrumbs.php',
    'json' => $baseDir.'/packages/projectorangebox/librarian/libraries/Json.php',
    'color' => $baseDir.'/packages/projectorangebox/librarian/libraries/Color.php',
    'parsedown' => $baseDir.'/packages/projectorangebox/librarian/libraries/Parsedown.php',
    'unzip' => $baseDir.'/packages/projectorangebox/librarian/libraries/Unzip.php',
    'curl' => $baseDir.'/packages/projectorangebox/librarian/libraries/Curl.php',
    'boost' => $baseDir.'/packages/projectorangebox/librarian/libraries/Boost.php',
    'cache_fragment' => $baseDir.'/packages/projectorangebox/librarian/libraries/Cache_fragment.php',
    'appvar' => $baseDir.'/packages/projectorangebox/librarian/libraries/Appvar.php',
    'sftp' => $baseDir.'/packages/projectorangebox/librarian/libraries/Sftp.php',
    'orange_tools' => $baseDir.'/packages/projectorangebox/migrations/libraries/Orange_tools.php',
    'migration_extras' => $baseDir.'/packages/projectorangebox/migrations/libraries/Migration_extras.php',
    'console' => $baseDir.'/packages/projectorangebox/migrations/libraries/Console.php',
    'scaffolding' => $baseDir.'/packages/projectorangebox/scaffolding/libraries/Scaffolding.php',
    'handlebars' => $baseDir.'/packages/projectorangebox/handlebars/libraries/Handlebars.php',
    'hbh_example_helpers' => $baseDir.'/packages/projectorangebox/handlebars/libraries/Hbh_example_helpers.php',
    'handlebars/handlebars_helpers' => $baseDir.'/packages/projectorangebox/handlebars/libraries/handlebars/Handlebars_helpers.php',
    'handlebars/handlebars_compiler' => $baseDir.'/packages/projectorangebox/handlebars/libraries/handlebars/Handlebars_compiler.php',
    'handlebars/handlebars_autoload_files' => $baseDir.'/packages/projectorangebox/handlebars/libraries/handlebars/Handlebars_autoload_files.php',
    'hbh_snippet' => $baseDir.'/packages/projectorangebox/handlebars/libraries/Hbh_snippet.php',
    'orange_autoload_files' => $baseDir.'/packages/projectorangebox/orange/libraries/Orange_autoload_files.php',
    'page' => $baseDir.'/packages/projectorangebox/orange/libraries/Page.php',
    'user' => $baseDir.'/packages/projectorangebox/orange/libraries/User.php',
    'validate' => $baseDir.'/packages/projectorangebox/orange/libraries/Validate.php',
    'cache_export' => $baseDir.'/packages/projectorangebox/orange/libraries/Cache_export.php',
    'errors' => $baseDir.'/packages/projectorangebox/orange/libraries/Errors.php',
    'xcache/my_cache' => $baseDir.'/packages/projectorangebox/orange/libraries/xCache/MY_Cache.php',
    'xcache/drivers/cache_export' => $baseDir.'/packages/projectorangebox/orange/libraries/xCache/drivers/Cache_export.php',
    'xcache/drivers/cache_app' => $baseDir.'/packages/projectorangebox/orange/libraries/xCache/drivers/Cache_app.php',
    'xcache/drivers/cache_page' => $baseDir.'/packages/projectorangebox/orange/libraries/xCache/drivers/Cache_page.php',
    'pear' => $baseDir.'/packages/projectorangebox/orange/libraries/Pear.php',
    'event' => $baseDir.'/packages/projectorangebox/orange/libraries/Event.php',
    'middleware_base' => $baseDir.'/packages/projectorangebox/orange/libraries/Middleware_base.php',
    'filter_base' => $baseDir.'/packages/projectorangebox/orange/libraries/Filter_base.php',
    'auth' => $baseDir.'/packages/projectorangebox/orange/libraries/Auth.php',
    'wallet' => $baseDir.'/packages/projectorangebox/orange/libraries/Wallet.php',
    'cache_app' => $baseDir.'/packages/projectorangebox/orange/libraries/Cache_app.php',
    'validate_base' => $baseDir.'/packages/projectorangebox/orange/libraries/Validate_base.php',
    'cache_page' => $baseDir.'/packages/projectorangebox/orange/libraries/Cache_page.php',
  ),
  'views' => 
  array (
    'admin/settings/details' => $baseDir.'/packages/projectorangebox/theme-orange/views/admin/settings/details.php',
    'admin/settings/editor' => $baseDir.'/packages/projectorangebox/theme-orange/views/admin/settings/editor.php',
    'admin/settings/index' => $baseDir.'/packages/projectorangebox/theme-orange/views/admin/settings/index.php',
    'admin/roles/details' => $baseDir.'/packages/projectorangebox/theme-orange/views/admin/roles/details.php',
    'admin/roles/index' => $baseDir.'/packages/projectorangebox/theme-orange/views/admin/roles/index.php',
    'admin/dashboard/index' => $baseDir.'/packages/projectorangebox/theme-orange/views/admin/dashboard/index.php',
    'admin/permissions/details' => $baseDir.'/packages/projectorangebox/theme-orange/views/admin/permissions/details.php',
    'admin/permissions/index' => $baseDir.'/packages/projectorangebox/theme-orange/views/admin/permissions/index.php',
    'admin/users/details' => $baseDir.'/packages/projectorangebox/theme-orange/views/admin/users/details.php',
    'admin/users/index' => $baseDir.'/application/views/admin/users/index.php',
    '_templates/orange_admin' => $baseDir.'/packages/projectorangebox/theme-orange/views/_templates/orange_admin.php',
    '_templates/access' => $baseDir.'/packages/projectorangebox/theme-orange/views/_templates/access.php',
    '_templates/nav' => $baseDir.'/application/views/_templates/nav.php',
    '_templates/footer' => $baseDir.'/packages/projectorangebox/theme-orange/views/_templates/footer.php',
    '_templates/blank' => $baseDir.'/packages/projectorangebox/theme-orange/views/_templates/blank.php',
    '_templates/header' => $baseDir.'/packages/projectorangebox/theme-orange/views/_templates/header.php',
    '_templates/orange_default' => $baseDir.'/packages/projectorangebox/theme-orange/views/_templates/orange_default.php',
    'login/index' => $baseDir.'/application/views/login/index.php',
    'login/inverted' => $baseDir.'/packages/projectorangebox/theme-orange/views/login/inverted.php',
    'errors/html/error_db' => $baseDir.'/application/views/errors/html/error_db.php',
    'errors/html/error_403' => $baseDir.'/application/views/errors/html/error_403.php',
    'errors/html/error_400' => $baseDir.'/application/views/errors/html/error_400.php',
    'errors/html/error_404' => $baseDir.'/application/views/errors/html/error_404.php',
    'errors/html/error_php' => $baseDir.'/application/views/errors/html/error_php.php',
    'errors/html/error_503' => $baseDir.'/packages/projectorangebox/theme-orange/views/errors/html/error_503.php',
    'errors/html/error_exception' => $baseDir.'/application/views/errors/html/error_exception.php',
    'errors/html/error_general' => $baseDir.'/application/views/errors/html/error_general.php',
    'errors/ajax/error_403' => $baseDir.'/application/views/errors/ajax/error_403.php',
    'errors/ajax/error_400' => $baseDir.'/application/views/errors/ajax/error_400.php',
    'errors/ajax/error_general' => $baseDir.'/application/views/errors/ajax/error_general.php',
    'errors/cli/error_db' => $baseDir.'/application/views/errors/cli/error_db.php',
    'errors/cli/error_400' => $baseDir.'/packages/projectorangebox/theme-orange/views/errors/cli/error_400.php',
    'errors/cli/error_404' => $baseDir.'/application/views/errors/cli/error_404.php',
    'errors/cli/error_php' => $baseDir.'/application/views/errors/cli/error_php.php',
    'errors/cli/error_exception' => $baseDir.'/application/views/errors/cli/error_exception.php',
    'errors/cli/error_general' => $baseDir.'/application/views/errors/cli/error_general.php',
    'users/edit_profile' => $baseDir.'/packages/projectorangebox/theme-orange/views/users/edit_profile.php',
    'admin/snippets/details' => $baseDir.'/packages/projectorangebox/general_addons/views/admin/snippets/details.php',
    'admin/snippets/index' => $baseDir.'/packages/projectorangebox/general_addons/views/admin/snippets/index.php',
    'admin/templates/details' => $baseDir.'/packages/projectorangebox/general_addons/views/admin/templates/details.php',
    'admin/templates/index' => $baseDir.'/packages/projectorangebox/general_addons/views/admin/templates/index.php',
    'handlebars/demo/index' => $baseDir.'/packages/projectorangebox/handlebars/views/handlebars/demo/index.php',
    'admin/configure/tooltips/details' => $baseDir.'/packages/projectorangebox/tooltips/views/admin/configure/tooltips/details.php',
    'admin/configure/tooltips/index' => $baseDir.'/packages/projectorangebox/tooltips/views/admin/configure/tooltips/index.php',
    'admin/reports/logins_successful/index' => $baseDir.'/packages/projectorangebox/login-success/views/admin/reports/logins_successful/index.php',
    'admin/utilities/cache_viewer/index' => $baseDir.'/packages/projectorangebox/cache-viewer/views/admin/utilities/cache_viewer/index.php',
    'migrate_help' => $baseDir.'/packages/projectorangebox/migrations/views/migrate_help.php',
    'fix_help' => $baseDir.'/packages/projectorangebox/migrations/views/fix_help.php',
    'cli/fix/git' => $baseDir.'/packages/projectorangebox/migrations/views/cli/fix/git.php',
    'admin/utilities/config_viewer/env' => $baseDir.'/packages/projectorangebox/config-viewer/views/admin/utilities/config_viewer/env.php',
    'admin/utilities/config_viewer/paths' => $baseDir.'/packages/projectorangebox/config-viewer/views/admin/utilities/config_viewer/paths.php',
    'admin/utilities/config_viewer/routes' => $baseDir.'/packages/projectorangebox/config-viewer/views/admin/utilities/config_viewer/routes.php',
    'admin/utilities/config_viewer/permissions' => $baseDir.'/packages/projectorangebox/config-viewer/views/admin/utilities/config_viewer/permissions.php',
    'admin/utilities/config_viewer/user' => $baseDir.'/packages/projectorangebox/config-viewer/views/admin/utilities/config_viewer/user.php',
    'admin/utilities/config_viewer/block' => $baseDir.'/packages/projectorangebox/config-viewer/views/admin/utilities/config_viewer/block.php',
    'admin/utilities/config_viewer/constants' => $baseDir.'/packages/projectorangebox/config-viewer/views/admin/utilities/config_viewer/constants.php',
    'admin/utilities/config_viewer/flush_acl' => $baseDir.'/packages/projectorangebox/config-viewer/views/admin/utilities/config_viewer/flush_acl.php',
    'admin/utilities/config_viewer/config' => $baseDir.'/packages/projectorangebox/config-viewer/views/admin/utilities/config_viewer/config.php',
    'admin/utilities/config_viewer/index' => $baseDir.'/packages/projectorangebox/config-viewer/views/admin/utilities/config_viewer/index.php',
    'admin/utilities/config_viewer/permissions_import' => $baseDir.'/packages/projectorangebox/config-viewer/views/admin/utilities/config_viewer/permissions_import.php',
    'admin/utilities/config_viewer/phpinfo' => $baseDir.'/packages/projectorangebox/config-viewer/views/admin/utilities/config_viewer/phpinfo.php',
    'admin/utilities/config_viewer/database_config' => $baseDir.'/packages/projectorangebox/config-viewer/views/admin/utilities/config_viewer/database_config.php',
    'admin/utilities/config_viewer/header' => $baseDir.'/packages/projectorangebox/config-viewer/views/admin/utilities/config_viewer/header.php',
    'admin/reports/opcache/org-index' => $baseDir.'/packages/projectorangebox/opcache/views/admin/reports/opcache/org-index.php',
    'admin/reports/opcache/index' => $baseDir.'/packages/projectorangebox/opcache/views/admin/reports/opcache/index.php',
    'admin/utilities/registration/index' => $baseDir.'/packages/projectorangebox/register/views/admin/utilities/registration/index.php',
    'user_registration/email/welcome_html' => $baseDir.'/packages/projectorangebox/register/views/user_registration/email/welcome_html.php',
    'user_registration/email/welcome_text' => $baseDir.'/packages/projectorangebox/register/views/user_registration/email/welcome_text.php',
    'user_registration/email/register_subject' => $baseDir.'/packages/projectorangebox/register/views/user_registration/email/register_subject.php',
    'user_registration/email/welcome_subject' => $baseDir.'/packages/projectorangebox/register/views/user_registration/email/welcome_subject.php',
    'user_registration/email/register_text' => $baseDir.'/packages/projectorangebox/register/views/user_registration/email/register_text.php',
    'user_registration/email/register_html' => $baseDir.'/packages/projectorangebox/register/views/user_registration/email/register_html.php',
    'user_registration/complete' => $baseDir.'/packages/projectorangebox/register/views/user_registration/complete.php',
    'user_registration/expired' => $baseDir.'/packages/projectorangebox/register/views/user_registration/expired.php',
    'user_registration/activate' => $baseDir.'/packages/projectorangebox/register/views/user_registration/activate.php',
    'user_registration/error' => $baseDir.'/packages/projectorangebox/register/views/user_registration/error.php',
    'user_registration/index' => $baseDir.'/packages/projectorangebox/register/views/user_registration/index.php',
    'errors/html/error_user_registration/error' => $baseDir.'/packages/projectorangebox/register/views/errors/html/error_user_registration/error.php',
    'forgot_password/sent' => $baseDir.'/packages/projectorangebox/forgot/views/forgot_password/sent.php',
    'forgot_password/new_password' => $baseDir.'/packages/projectorangebox/forgot/views/forgot_password/new_password.php',
    'forgot_password/email/forgot_text' => $baseDir.'/packages/projectorangebox/forgot/views/forgot_password/email/forgot_text.php',
    'forgot_password/email/forgot_html' => $baseDir.'/packages/projectorangebox/forgot/views/forgot_password/email/forgot_html.php',
    'forgot_password/email/forgot_subject' => $baseDir.'/packages/projectorangebox/forgot/views/forgot_password/email/forgot_subject.php',
    'forgot_password/changed' => $baseDir.'/packages/projectorangebox/forgot/views/forgot_password/changed.php',
    'forgot_password/error' => $baseDir.'/packages/projectorangebox/forgot/views/forgot_password/error.php',
    'forgot_password/index' => $baseDir.'/packages/projectorangebox/forgot/views/forgot_password/index.php',
    'dropships/details' => $baseDir.'/packages/quadratec/drop-ships/views/dropships/details.php',
    'dropships/_dropship_repeatable' => $baseDir.'/packages/quadratec/drop-ships/views/dropships/_dropship_repeatable.php',
    'dropships/index' => $baseDir.'/packages/quadratec/drop-ships/views/dropships/index.php',
    'admin/dropships/details' => $baseDir.'/packages/quadratec/drop-ships/views/admin/dropships/details.php',
    'admin/dropships/index' => $baseDir.'/packages/quadratec/drop-ships/views/admin/dropships/index.php',
    'stock_status_check/details' => $baseDir.'/packages/quadratec/stock-status-check/views/stock_status_check/details.php',
    'stock_status_check/display_part_no' => $baseDir.'/packages/quadratec/stock-status-check/views/stock_status_check/display_part_no.php',
    'stock_status_check/index' => $baseDir.'/packages/quadratec/stock-status-check/views/stock_status_check/index.php',
    'backorder_call_center/details' => $baseDir.'/packages/quadratec/backorder/views/backorder_call_center/details.php',
    'backorder_call_center/table_body' => $baseDir.'/packages/quadratec/backorder/views/backorder_call_center/table_body.php',
    'backorder_call_center/index' => $baseDir.'/packages/quadratec/backorder/views/backorder_call_center/index.php',
    'backorder_call_center/po_details' => $baseDir.'/packages/quadratec/backorder/views/backorder_call_center/po_details.php',
    'admin/backorder_buyer/details' => $baseDir.'/packages/quadratec/backorder/views/admin/backorder_buyer/details.php',
    'admin/backorder_buyer/index' => $baseDir.'/packages/quadratec/backorder/views/admin/backorder_buyer/index.php',
    'admin/backorder/details' => $baseDir.'/packages/quadratec/backorder/views/admin/backorder/details.php',
    'admin/backorder/table_body' => $baseDir.'/packages/quadratec/backorder/views/admin/backorder/table_body.php',
    'admin/backorder/index' => $baseDir.'/packages/quadratec/backorder/views/admin/backorder/index.php',
    'admin/backorder/po_details' => $baseDir.'/packages/quadratec/backorder/views/admin/backorder/po_details.php',
    'admin/backorder_status/details' => $baseDir.'/packages/quadratec/backorder/views/admin/backorder_status/details.php',
    'admin/backorder_status/index' => $baseDir.'/packages/quadratec/backorder/views/admin/backorder_status/index.php',
    'blogs/details' => $baseDir.'/application/views/blogs/details.php',
    'blogs/index' => $baseDir.'/application/views/blogs/index.php',
    'main/index_block' => $baseDir.'/application/views/main/index_block.php',
    'main/index' => $baseDir.'/application/views/main/index.php',
  ),
  'controllers' => 
  array (
    'admin/reports/logins_successful(.*)' => 
    array (
      'package' => 'packages/projectorangebox/login-success/',
      'directory' => '../../packages/projectorangebox/login-success/controllers/admin/reports/',
      'controller' => '/var/www/www/app/packages/projectorangebox/login-success/controllers/admin/reports/Logins_successfulController.php',
      'clean_controller' => 'Logins_successful',
    ),
    'admin/utilities/config_viewer(.*)' => 
    array (
      'package' => 'packages/projectorangebox/config-viewer/',
      'directory' => '../../packages/projectorangebox/config-viewer/controllers/admin/utilities/',
      'controller' => '/var/www/www/app/packages/projectorangebox/config-viewer/controllers/admin/utilities/Config_viewerController.php',
      'clean_controller' => 'Config_viewer',
    ),
    'admin/utilities/cache_viewer(.*)' => 
    array (
      'package' => 'packages/projectorangebox/cache-viewer/',
      'directory' => '../../packages/projectorangebox/cache-viewer/controllers/admin/utilities/',
      'controller' => '/var/www/www/app/packages/projectorangebox/cache-viewer/controllers/admin/utilities/Cache_viewerController.php',
      'clean_controller' => 'Cache_viewer',
    ),
    'admin/utilities/registration(.*)' => 
    array (
      'package' => 'packages/projectorangebox/register/',
      'directory' => '../../packages/projectorangebox/register/controllers/admin/utilities/',
      'controller' => '/var/www/www/app/packages/projectorangebox/register/controllers/admin/utilities/RegistrationController.php',
      'clean_controller' => 'Registration',
    ),
    'admin/configure/tooltips(.*)' => 
    array (
      'package' => 'packages/projectorangebox/tooltips/',
      'directory' => '../../packages/projectorangebox/tooltips/controllers/admin/configure/',
      'controller' => '/var/www/www/app/packages/projectorangebox/tooltips/controllers/admin/configure/TooltipsController.php',
      'clean_controller' => 'Tooltips',
    ),
    'cli/auto_add_permissions(.*)' => 
    array (
      'package' => 'packages/projectorangebox/migrations/',
      'directory' => '../../packages/projectorangebox/migrations/controllers/cli/',
      'controller' => '/var/www/www/app/packages/projectorangebox/migrations/controllers/cli/Auto_add_permissionsController.php',
      'clean_controller' => 'Auto_add_permissions',
    ),
    'admin/backorder_status(.*)' => 
    array (
      'package' => 'packages/quadratec/backorder/',
      'directory' => '../../packages/quadratec/backorder/controllers/admin/',
      'controller' => '/var/www/www/app/packages/quadratec/backorder/controllers/admin/Backorder_statusController.php',
      'clean_controller' => 'Backorder_status',
    ),
    'admin/reports/opcache(.*)' => 
    array (
      'package' => 'packages/projectorangebox/opcache/',
      'directory' => '../../packages/projectorangebox/opcache/controllers/admin/reports/',
      'controller' => '/var/www/www/app/packages/projectorangebox/opcache/controllers/admin/reports/OpcacheController.php',
      'clean_controller' => 'Opcache',
    ),
    'backorder_call_center(.*)' => 
    array (
      'package' => 'packages/quadratec/backorder/',
      'directory' => '../../packages/quadratec/backorder/controllers/',
      'controller' => '/var/www/www/app/packages/quadratec/backorder/controllers/Backorder_call_centerController.php',
      'clean_controller' => 'Backorder_call_center',
    ),
    'admin/backorder_buyer(.*)' => 
    array (
      'package' => 'packages/quadratec/backorder/',
      'directory' => '../../packages/quadratec/backorder/controllers/admin/',
      'controller' => '/var/www/www/app/packages/quadratec/backorder/controllers/admin/Backorder_buyerController.php',
      'clean_controller' => 'Backorder_buyer',
    ),
    'stock_status_check(.*)' => 
    array (
      'package' => 'packages/quadratec/stock-status-check/',
      'directory' => '../../packages/quadratec/stock-status-check/controllers/',
      'controller' => '/var/www/www/app/packages/quadratec/stock-status-check/controllers/Stock_status_checkController.php',
      'clean_controller' => 'Stock_status_check',
    ),
    'admin/permissions(.*)' => 
    array (
      'package' => 'packages/projectorangebox/theme-orange/',
      'directory' => '../../packages/projectorangebox/theme-orange/controllers/admin/',
      'controller' => '/var/www/www/app/packages/projectorangebox/theme-orange/controllers/admin/PermissionsController.php',
      'clean_controller' => 'Permissions',
    ),
    'user_registration(.*)' => 
    array (
      'package' => 'packages/projectorangebox/register/',
      'directory' => '../../packages/projectorangebox/register/controllers/',
      'controller' => '/var/www/www/app/packages/projectorangebox/register/controllers/User_registrationController.php',
      'clean_controller' => 'User_registration',
    ),
    'tooltips_handler(.*)' => 
    array (
      'package' => 'packages/projectorangebox/tooltips/',
      'directory' => '../../packages/projectorangebox/tooltips/controllers/',
      'controller' => '/var/www/www/app/packages/projectorangebox/tooltips/controllers/Tooltips_handlerController.php',
      'clean_controller' => 'Tooltips_handler',
    ),
    'handlebars/demo(.*)' => 
    array (
      'package' => 'packages/projectorangebox/handlebars/',
      'directory' => '../../packages/projectorangebox/handlebars/controllers/handlebars/',
      'controller' => '/var/www/www/app/packages/projectorangebox/handlebars/controllers/handlebars/DemoController.php',
      'clean_controller' => 'Demo',
    ),
    'admin/templates(.*)' => 
    array (
      'package' => 'packages/projectorangebox/general_addons/',
      'directory' => '../../packages/projectorangebox/general_addons/controllers/admin/',
      'controller' => '/var/www/www/app/packages/projectorangebox/general_addons/controllers/admin/TemplatesController.php',
      'clean_controller' => 'Templates',
    ),
    'cli/scaffolding(.*)' => 
    array (
      'package' => 'packages/projectorangebox/scaffolding/',
      'directory' => '../../packages/projectorangebox/scaffolding/controllers/cli/',
      'controller' => '/var/www/www/app/packages/projectorangebox/scaffolding/controllers/cli/ScaffoldingController.php',
      'clean_controller' => 'Scaffolding',
    ),
    'admin/dashboard(.*)' => 
    array (
      'package' => 'packages/projectorangebox/theme-orange/',
      'directory' => '../../packages/projectorangebox/theme-orange/controllers/admin/',
      'controller' => '/var/www/www/app/packages/projectorangebox/theme-orange/controllers/admin/DashboardController.php',
      'clean_controller' => 'Dashboard',
    ),
    'forgot_password(.*)' => 
    array (
      'package' => 'packages/projectorangebox/forgot/',
      'directory' => '../../packages/projectorangebox/forgot/controllers/',
      'controller' => '/var/www/www/app/packages/projectorangebox/forgot/controllers/Forgot_passwordController.php',
      'clean_controller' => 'Forgot_password',
    ),
    'admin/dropships(.*)' => 
    array (
      'package' => 'packages/quadratec/drop-ships/',
      'directory' => '../../packages/quadratec/drop-ships/controllers/admin/',
      'controller' => '/var/www/www/app/packages/quadratec/drop-ships/controllers/admin/DropshipsController.php',
      'clean_controller' => 'Dropships',
    ),
    'admin/backorder(.*)' => 
    array (
      'package' => 'packages/quadratec/backorder/',
      'directory' => '../../packages/quadratec/backorder/controllers/admin/',
      'controller' => '/var/www/www/app/packages/quadratec/backorder/controllers/admin/BackorderController.php',
      'clean_controller' => 'Backorder',
    ),
    'admin/snippets(.*)' => 
    array (
      'package' => 'packages/projectorangebox/general_addons/',
      'directory' => '../../packages/projectorangebox/general_addons/controllers/admin/',
      'controller' => '/var/www/www/app/packages/projectorangebox/general_addons/controllers/admin/SnippetsController.php',
      'clean_controller' => 'Snippets',
    ),
    'admin/settings(.*)' => 
    array (
      'package' => 'packages/projectorangebox/theme-orange/',
      'directory' => '../../packages/projectorangebox/theme-orange/controllers/admin/',
      'controller' => '/var/www/www/app/packages/projectorangebox/theme-orange/controllers/admin/SettingsController.php',
      'clean_controller' => 'Settings',
    ),
    'cli/backorder(.*)' => 
    array (
      'package' => 'packages/quadratec/backorder/',
      'directory' => '../../packages/quadratec/backorder/controllers/cli/',
      'controller' => '/var/www/www/app/packages/quadratec/backorder/controllers/cli/BackorderController.php',
      'clean_controller' => 'Backorder',
    ),
    'admin/roles(.*)' => 
    array (
      'package' => 'packages/projectorangebox/theme-orange/',
      'directory' => '../../packages/projectorangebox/theme-orange/controllers/admin/',
      'controller' => '/var/www/www/app/packages/projectorangebox/theme-orange/controllers/admin/RolesController.php',
      'clean_controller' => 'Roles',
    ),
    'admin/users(.*)' => 
    array (
      'package' => 'packages/projectorangebox/theme-orange/',
      'directory' => '../../packages/projectorangebox/theme-orange/controllers/admin/',
      'controller' => '/var/www/www/app/packages/projectorangebox/theme-orange/controllers/admin/UsersController.php',
      'clean_controller' => 'Users',
    ),
    'cli/migrate(.*)' => 
    array (
      'package' => 'packages/projectorangebox/migrations/',
      'directory' => '../../packages/projectorangebox/migrations/controllers/cli/',
      'controller' => '/var/www/www/app/packages/projectorangebox/migrations/controllers/cli/MigrateController.php',
      'clean_controller' => 'Migrate',
    ),
    'handlebars(.*)' => 
    array (
      'package' => 'packages/projectorangebox/handlebars/',
      'directory' => '../../packages/projectorangebox/handlebars/controllers/',
      'controller' => '/var/www/www/app/packages/projectorangebox/handlebars/controllers/HandlebarsController.php',
      'clean_controller' => 'Handlebars',
    ),
    'dropships(.*)' => 
    array (
      'package' => 'packages/quadratec/drop-ships/',
      'directory' => '../../packages/quadratec/drop-ships/controllers/',
      'controller' => '/var/www/www/app/packages/quadratec/drop-ships/controllers/DropshipsController.php',
      'clean_controller' => 'Dropships',
    ),
    'login(.*)' => 
    array (
      'package' => 'packages/projectorangebox/theme-orange/',
      'directory' => '../../packages/projectorangebox/theme-orange/controllers/',
      'controller' => '/var/www/www/app/packages/projectorangebox/theme-orange/controllers/LoginController.php',
      'clean_controller' => 'Login',
    ),
    'users(.*)' => 
    array (
      'package' => 'packages/projectorangebox/theme-orange/',
      'directory' => '../../packages/projectorangebox/theme-orange/controllers/',
      'controller' => '/var/www/www/app/packages/projectorangebox/theme-orange/controllers/UsersController.php',
      'clean_controller' => 'Users',
    ),
    'main(.*)' => 
    array (
      'package' => 'application/',
      'directory' => '../../application/controllers/',
      'controller' => '/var/www/www/app/application/controllers/MainController.php',
      'clean_controller' => 'Main',
    ),
  ),
);